### ISSUE TITLE
Вынесит конфиг для сервиса авторизации в .env

### ISSUE THREAD

**Issue by maxism** [UtfCube/training#1]

**Comment by UtfCube** [comment]
@maxism есть вот такая штука https://docs.nestjs.com/v5/techniques/configuration, или не заморачиваться и просто закинуть все в .env?

**Comment by maxism** [comment]
Вот как раз с помощью этой штуки и нужно читать переменные окружения, размещенные в файле .env.

С уважением, Максим Ульянов.
Веб-сайт: www.maxism.ru <http://www.maxism.ru/>.

**Comment by maxism** [comment]
@UtfCube добавь в репозиторий env.example, чтобы из него можно было быстро развертывать .env файл, а не искать какие опции где используются.
