### ISSUE TITLE
GET /user должен по токену возвращать инфу о юзере

### ISSUE THREAD

**Issue by maxism** [UtfCube/training#2]

**Comment by UtfCube** [comment]
в инфу входит история тренировок?

**Comment by maxism** [comment]
@UtfCube нет, для этого отдельный эндпоинт сделаем.

**Comment by UtfCube** [comment]
он кстати есть там уже

**Comment by maxism** [comment]
@UtfCube не вижу в контроллере.

**Comment by UtfCube** [comment]
в training.controller

**Comment by UtfCube** [comment]
добавил endpoint
