### ISSUE TITLE
GET /history должен возвращать историю тренировок

### ISSUE THREAD

**Issue by maxism** [UtfCube/training#3]
История тренировок должна работать с пагинацией: указываем в запросе page, offset и limit.

**Comment by UtfCube** [comment]
сделаю тогда в контроллере для user и endpoint будет /user/history

**Comment by maxism** [comment]
@UtfCube не, так не пойдет. Все таки нужно по REST разделять ответственность между различными контроллерами, в каждом контроллере свой кусок ответственности.

**Comment by maxism** [comment]
Все таки у тебя сейчас есть отдельная сущность в системе History.

**Comment by UtfCube** [comment]
под нее свой контроллер и тд

**Comment by UtfCube** [comment]
@maxism page offset и limit как параметры GET запроса или как json тело POST?

**Comment by maxism** [comment]
@UtfCube привыкни, что у GET запроса не может быть тела. Так что здесь нужно мониторить именно параметры GET запроса :)

**Comment by UtfCube** [comment]
@maxism что делают page и limit?

**Comment by UtfCube** [comment]
limit я так понимаю, это количество записей на странице, offset сдвиг от начала массива с историей, тогда page для чего нужен?

**Comment by maxism** [comment]
Да, ты прав. Нам нужен только limit и page.

**Comment by UtfCube** [comment]
limit и offset*?

**Comment by maxism** [comment]
page и limit. Здесь вопрос в том, чтобы фронту нужно было осуществлять меньше манипуляций для организации пагинации. При этом нужно в ответе сервера положить еще параметр total — который будет считать сколько всего найдено результатов, чтобы на основе limit и total посчитать сколько всего страниц есть.

С уважением, Максим Ульянов.
Веб-сайт: www.maxism.ru <http://www.maxism.ru/>.

**Comment by UtfCube** [comment]
@maxism добавил пагинацию

**Comment by UtfCube** [comment]
@maxism  обновил пагинацию

**Comment by maxism** [comment]
для первой реализации пойдет, но ты придумал то, что уже есть в TypeOrm. 
```ts
const [ total, trainings ] = await this.trainingRepository.findAndCount({
            where: {
                user: {
                    id: user_id
                }
            },
            relations: ['exercises'],
            skip: (page - 1) * limit,
            take: limit
        });
```
